defaults: &defaults
  host: localhost
  port: 27017
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: locomotive_dev

test:
  <<: *defaults
  database: locomotive_test

# set these environment variables on your prod server
production:
  max_retries_on_connection_failure: 3
  # <<: *defaults
  # database: locomotive_prod

  # other settings for production
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>

  # heroku
  # uri: <%= ENV['MONGOHQ_URL'] %>

  # bushido (mongohq_url will also work)
  #uri: <%= ENV['MONGODB_URL'] %>

  #host: mongodb0.locum.ru
  #port: 27017
  #username: fkonstan_new-t13
  #password: OrnrD1Qp
  #database: fkonstan_new-t13

  <<: *defaults
  database: locomotive_test